COMPARE_POINTWISE_IMPORTANT_FEATURES = [
    "response_length_left",
    "prev_response_A_gaze_window_002",
    "gaze_max_char_position_reached",
    "gaze_max_idx_left",
    "prev_response_A_mouse_window_002",
    "prev_response_A_gaze_normalized_avg_char_position",
    "prev_gaze_max_idx_ratio_left",
    "mouse_max_char_position_reached",
    "mouse_offscreen_time_reviewing_s",
    "prev_response_A_gaze_window_017",
    "prev_mouse_offscreen_time_composing_s",
    "prev_response_A_mouse_normalized_char_position_variance",
    "prev_response_A_mouse_window_000",
    "prev_gaze_composing_duration_s",
    "prev_mouse_composing_duration_s",
    "prev_cross_modality_reviewing_duration_ratio_gaze_mouse",
    "prev_mouse_reviewing_offscreen_ratio",
    "prev_mouse_composing_pct",
    "mouse_composing_active_ratio",
    "prev_mouse_lookback_time_s",
    "prev_response_A_gaze_normalized_char_position_variance",
    "prev_response_A_mouse_window_006",
    "prev_response_A_mouse_focused_engagement_ratio",
    "prev_response_A_gaze_window_000",
    "response_A_mouse_normalized_avg_char_position",
    "prev_gaze_reviewing_active_ratio",
    "prev_gaze_active_time_composing_s",
    "prev_gaze_composing_offscreen_ratio",
    "prev_response_A_gaze_window_003",
    "prev_response_A_mouse_window_001",
    "prev_cross_modality_composing_activity_ratio_gaze_mouse",
    "prev_mouse_reviewing_pct",
    "prev_gaze_offscreen_increase",
    "mouse_reviewing_composing_activity_ratio",
    "prev_mouse_active_time_composing_s",
    "prev_user_query_length",
    "mouse_lookback_time_s",
    "prev_response_A_gaze_window_018",
    "mouse_composing_reviewing_activity_diff",
    "prev_response_A_mouse_overall_attention_ratio",
    "gaze_reviewing_duration_s",
    "prev_response_A_gaze_window_001",
    "prev_mouse_reviewing_composing_activity_ratio",
    "prev_gaze_lookback_time_s",
    "mouse_reviewing_duration_s",
    "prev_gaze_composing_reviewing_activity_diff",
    "mouse_composing_lookback_ratio",
    "mouse_reviewing_pct",
    "prev_mouse_reviewing_duration_s",
    "prev_gaze_reviewing_composing_duration_ratio",
]

COMPARE_POINTWISE_GAZE_FEATURES = [
        "response_length_left",
    "prev_response_A_gaze_window_002",
    "gaze_max_char_position_reached",
    "gaze_max_idx_left",
    "prev_response_A_gaze_normalized_avg_char_position",
    "prev_gaze_max_idx_ratio_left",
    "prev_response_A_gaze_window_017",
    "prev_gaze_composing_duration_s",
    "prev_response_A_gaze_normalized_char_position_variance",
    "prev_response_A_gaze_window_000",
    "prev_gaze_reviewing_active_ratio",
    "prev_gaze_active_time_composing_s",
    "prev_gaze_composing_offscreen_ratio",
    "prev_response_A_gaze_window_003",
    "prev_gaze_offscreen_increase",
    "prev_user_query_length",
    "prev_response_A_gaze_window_018",
    "gaze_reviewing_duration_s",
    "prev_response_A_gaze_window_001",
    "prev_gaze_lookback_time_s",
    "prev_gaze_composing_reviewing_activity_diff",
    "prev_gaze_reviewing_composing_duration_ratio",
]

COMPARE_POINTWISE_MOUSE_FEATURES = [
    "response_length_left",
    "prev_response_A_mouse_window_002",
    "mouse_max_char_position_reached",
    "mouse_offscreen_time_reviewing_s",
    "prev_mouse_offscreen_time_composing_s",
    "prev_response_A_mouse_normalized_char_position_variance",
    "prev_response_A_mouse_window_000",
    "prev_mouse_composing_duration_s",
    "prev_mouse_reviewing_offscreen_ratio",
    "prev_mouse_composing_pct",
    "mouse_composing_active_ratio",
    "prev_mouse_lookback_time_s",
    "prev_response_A_mouse_window_006",
    "prev_response_A_mouse_focused_engagement_ratio",
    "response_A_mouse_normalized_avg_char_position",
    "prev_response_A_mouse_window_001",
    "prev_mouse_reviewing_pct",
    "mouse_reviewing_composing_activity_ratio",
    "prev_mouse_active_time_composing_s",
    "prev_user_query_length",
    "mouse_lookback_time_s",
    "mouse_composing_reviewing_activity_diff",
    "prev_response_A_mouse_overall_attention_ratio",
    "prev_mouse_reviewing_composing_activity_ratio",
    "mouse_reviewing_duration_s",
    "mouse_composing_lookback_ratio",
    "mouse_reviewing_pct",
    "prev_mouse_reviewing_duration_s",
]

# COMPARE_POINTWISE_IMPORTANT_FEATURES = [
#     "response_length_left",
#     "mouse_max_char_position_reached",
#     "mouse_max_idx_ratio_left",
#     "prev_response_A_mouse_window_002",
#     "prev_response_A_gaze_window_002",
#     "gaze_max_idx_left",
#     "mouse_composing_active_ratio",
#     "gaze_max_char_position_reached",
#     "prev_gaze_max_idx_ratio_left",
#     "prev_mouse_lookback_time_s",
#     "prev_mouse_composing_duration_s",
#     "prev_response_A_gaze_window_001",
#     "prev_gaze_max_char_position_reached",
#     "prev_gaze_max_idx_left",
#     "prev_mouse_max_char_position_reached",
#     "prev_gaze_offscreen_increase",
#     "prev_mouse_reviewing_offscreen_ratio",
#     "prev_response_A_gaze_normalized_avg_char_position",
#     "prev_response_A_mouse_normalized_avg_char_position",
#     "prev_response_A_mouse_window_000",
#     "prev_gaze_active_time_composing_s",
#     "gaze_offscreen_time_reviewing_s",
#     "prev_camera_green",
#     "prev_response_A_gaze_window_003",
#     "prev_mouse_reviewing_composing_activity_ratio",
#     "prev_cross_modality_reviewing_duration_ratio_gaze_mouse",
#     "cross_modality_reviewing_activity_ratio_gaze_mouse",
#     "mouse_reviewing_composing_duration_ratio",
#     "prev_response_A_mouse_window_001",
#     "prev_mouse_reviewing_pct",
#     "prev_mouse_composing_pct",
#     "prev_mouse_max_idx_ratio_left",
#     "gaze_reviewing_offscreen_ratio",
#     "gaze_reviewing_duration_s",
#     "prev_mouse_offscreen_time_composing_s",
#     "prev_gaze_reviewing_offscreen_ratio",
#     "prev_response_A_gaze_window_004",
#     "response_A_gaze_focused_engagement_ratio",
#     "gaze_composing_pct",
#     "prev_gaze_active_time_reviewing_s",
#     "prev_user_query_length",
#     "mouse_active_time_reviewing_s",
#     "gaze_lookback_time_s",
#     "prev_gaze_lookback_time_s",
#     "prev_response_A_gaze_normalized_char_position_variance",
#     "cross_modality_composing_duration_ratio_gaze_mouse",
#     "camera_green",
#     "gaze_composing_duration_s",
#     "mouse_composing_lookback_ratio",
#     "mouse_active_time_composing_s",
# ]

# COMPARE_POINTWISE_GAZE_FEATURES = [
#     "response_length_left",
#     "prev_response_A_gaze_window_002",
#     "gaze_max_idx_left",
#     "gaze_max_char_position_reached",
#     "prev_gaze_max_idx_ratio_left",
#     "prev_response_A_gaze_window_001",
#     "prev_gaze_max_char_position_reached",
#     "prev_gaze_max_idx_left",
#     "prev_gaze_offscreen_increase",
#     "prev_response_A_gaze_normalized_avg_char_position",
#     "prev_gaze_active_time_composing_s",
#     "gaze_offscreen_time_reviewing_s",
#     "prev_camera_green",
#     "prev_response_A_gaze_window_003",
#     "gaze_reviewing_offscreen_ratio",
#     "gaze_reviewing_duration_s",
#     "prev_gaze_reviewing_offscreen_ratio",
#     "prev_response_A_gaze_window_004",
#     "response_A_gaze_focused_engagement_ratio",
#     "gaze_composing_pct",
#     "prev_gaze_active_time_reviewing_s",
#     "prev_user_query_length",
#     "gaze_lookback_time_s",
#     "prev_gaze_lookback_time_s",
#     "prev_response_A_gaze_normalized_char_position_variance",
#     "camera_green",
#     "gaze_composing_duration_s",
# ]

# COMPARE_POINTWISE_MOUSE_FEATURES = [
#     "response_length_left",
#     "mouse_max_char_position_reached",
#     "mouse_max_idx_ratio_left",
#     "prev_response_A_mouse_window_002",
#     "mouse_composing_active_ratio",
#     "prev_mouse_lookback_time_s",
#     "prev_mouse_composing_duration_s",
#     "prev_mouse_reviewing_offscreen_ratio",
#     "prev_response_A_mouse_normalized_avg_char_position",
#     "prev_response_A_mouse_window_000",
#     "prev_camera_green",
#     "prev_mouse_reviewing_composing_activity_ratio",
#     "mouse_reviewing_composing_duration_ratio",
#     "prev_response_A_mouse_window_001",
#     "prev_mouse_reviewing_pct",
#     "prev_mouse_composing_pct",
#     "prev_mouse_max_idx_ratio_left",
#     "prev_mouse_offscreen_time_composing_s",
#     "prev_user_query_length",
#     "mouse_active_time_reviewing_s",
#     "camera_green",
#     "mouse_composing_lookback_ratio",
#     "mouse_active_time_composing_s",
# ]

PAIRWISE_IMPORTANT_FEATURES = [
    "mouse_max_idx_right",
    "gaze_left_reviewing_engaged_time_s",
    "gaze_max_idx_right",
    "response_A_gaze_overall_attention_ratio",
    "response_length_left",
    "user_query_length",
    "response_B_mouse_overall_attention_ratio",
    "gaze_total_entries_right",
    "response_length_right",
    "response_B_mouse_focused_engagement_ratio",
    "gaze_right_reviewing_engaged_time_s",
    "response_A_gaze_focused_engagement_ratio",
    "response_A_gaze_window_001",
    "gaze_max_idx_left",
    "gaze_onscreen_points_right",
    "response_A_mouse_overall_attention_ratio",
    "mouse_onscreen_points_right",
    "response_B_gaze_window_019",
    "response_A_mouse_focused_engagement_ratio",
    "mouse_max_idx_left",
    "mouse_comparison_reviewing_time_ratio",
    "mouse_total_entries_right",
    "response_B_gaze_overall_attention_ratio",
    "mouse_comparison_reviewing_time_diff",
    "mouse_total_entries_left",
    "gaze_left_reviewing_engaged_pct",
    "response_B_gaze_window_002",
    "mouse_comparison_which_side_read_further",
    "response_A_gaze_window_000",
    "gaze_onscreen_points_left",
    "cross_modality_right_reviewing_duration_ratio_gaze_mouse",
    "mouse_right_reviewing_onscreen_ratio",
    "cross_modality_left_reviewing_duration_ratio_gaze_mouse",
    "gaze_total_entries_left",
    "gaze_left_reviewing_active_ratio",
    "response_A_gaze_normalized_avg_char_position",
    "response_B_mouse_window_019",
    "mouse_right_reviewing_offscreen_ratio",
    "response_A_mouse_window_000",
    "camera_green",
    "mouse_max_idx_ratio_right",
    "gaze_right_reviewing_onscreen_ratio",
    "response_A_gaze_window_002",
    "gaze_right_reviewing_offscreen_ratio",
    "mouse_left_reviewing_onscreen_ratio",
    "response_A_mouse_normalized_avg_char_position",
    "mouse_comparison_reviewing_activity_ratio",
    "response_B_gaze_window_000",
    "gaze_left_reviewing_onscreen_ratio",
    "mouse_onscreen_points_left",
]


PAIRWISE_GAZE_IMPORTANT = [
    "gaze_left_reviewing_engaged_time_s",
    "gaze_max_idx_right",
    "response_A_gaze_overall_attention_ratio",
    "response_length_left",
    "user_query_length",
    "gaze_total_entries_right",
    "response_length_right",
    "gaze_right_reviewing_engaged_time_s",
    "response_A_gaze_focused_engagement_ratio",
    "response_A_gaze_window_001",
    "gaze_max_idx_left",
    "gaze_onscreen_points_right",
    "response_B_gaze_window_019",
    "response_B_gaze_overall_attention_ratio",
    "gaze_left_reviewing_engaged_pct",
    "response_B_gaze_window_002",
    "response_A_gaze_window_000",
    "gaze_onscreen_points_left",
    "gaze_total_entries_left",
    "gaze_left_reviewing_active_ratio",
    "response_A_gaze_normalized_avg_char_position",
    "camera_green",
    "gaze_right_reviewing_onscreen_ratio",
    "response_A_gaze_window_002",
    "gaze_right_reviewing_offscreen_ratio",
    "response_B_gaze_window_000",
    "gaze_left_reviewing_onscreen_ratio",
]

PAIRWISE_MOUSE_IMPORTANT = [
    "mouse_max_idx_right",
    "response_length_left",
    "user_query_length",
    "response_B_mouse_overall_attention_ratio",
    "response_length_right",
    "response_B_mouse_focused_engagement_ratio",
    "response_A_mouse_overall_attention_ratio",
    "mouse_onscreen_points_right",
    "response_A_mouse_focused_engagement_ratio",
    "mouse_max_idx_left",
    "mouse_comparison_reviewing_time_ratio",
    "mouse_total_entries_right",
    "mouse_comparison_reviewing_time_diff",
    "mouse_total_entries_left",
    "mouse_comparison_which_side_read_further",
    "mouse_right_reviewing_onscreen_ratio",
    "response_B_mouse_window_019",
    "mouse_right_reviewing_offscreen_ratio",
    "response_A_mouse_window_000",
    "camera_green",
    "mouse_max_idx_ratio_right",
    "mouse_left_reviewing_onscreen_ratio",
    "response_A_mouse_normalized_avg_char_position",
    "mouse_comparison_reviewing_activity_ratio",
    "mouse_onscreen_points_left",
]